name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true # Cancel older runs for the same PR/branch

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: swift build

      - name: Test
        run: swift test --parallel
